language: ruby
cache: bundler
bundler_args: --without development production assets
rvm:
  - 2.3.1
script:
  - bundle exec rspec spec/
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database kronos_test;' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare