language: ruby
rvm:
  - 1.9.3
script:
  - bundle exec rspec spec/
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database kronos_test;' -U postgres
  - bundle exec rake db:test:prepare
	