# Base image
FROM ruby:2.3.1

ENV HOME /home/rails/webapp
ENV RAILS_ENV development

# Allow APT to communicate over HTTPS
# Add passenger repo to sources
RUN apt-get update -qq && apt-get install -y apt-transport-https ca-certificates \
    && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 \
    # Install PGsql dependencies,js engine and passenger
    && echo deb https://oss-binaries.phusionpassenger.com/apt/passenger jessie main > /etc/apt/sources.list.d/passenger.list \
    && apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs ghostscript nginx-extras passenger \
    && useradd kronos

WORKDIR $HOME

COPY Gemfile* $HOME/

# Make the app user owner of the app folder
RUN chown -R kronos $HOME

USER kronos

# Gems will be installed later
ENV BUNDLE_PATH /bundler-cache

RUN gem install bundler

USER root