version: '2'
services:
  db:
    image: postgres:9.1.22
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    command: bundle exec passenger start
  worker:
    build: .
    depends_on:
      - db
    env_file: .env
    command: bundle exec rake jobs:work
  owncloud:
    image: owncloud:9-apache
    depends_on:
      - db
    ports:
      - "1337:80"
  db_backup:
    image: protowouter/kronos-backup
    depends_on:
      - db
  db_backupserver:
    image: protowouter/kronos-backupserver
    env_file: .backupserver.env
    ports:
      - "1022:22"