version: '2'
services:
  db:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: kronos
  app:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    command: sh ./script/start_app.sh
    volumes:
      # Path on the host, relative to the Compose file
      - ./:/home/app:cached

