version: "3.0"
name: kronoswebsite
volumes:
  node_modules:
  bundle:
  packs:
  postgres:
services:
  app:
    image: kronos-app:rails6.1.6
    build:
      context: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    tmpfs: /app/tmp
    volumes:
      # Path on the host, relative to the Compose file
      - .:/app
      - node_modules:/app/node_modules
      - bundle:/app/vendor/bundle
      - packs:/app/public/packs
  db:
    image: postgres:12.6
    environment:
      POSTGRES_PASSWORD: kronos
    volumes:
      - postgres:/var/lib/postgresql/data

