version: '2'
services:
  db:
    image: postgres:9.3
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    command: bundle exec passenger start
  worker:
    build: .
    depends_on:
      - db
    env_file: .env
    command: bundle exec rake jobs:work