version: '2'
services:
  db:
    image: postgres:9.1.22
  app:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - "3000:3000"
      - "3035:3035"
      - "8888:8888"
    depends_on:
      - db
    env_file: .env
    command: sh ./script/start_app_development.sh
    volumes:
      # Path on the host, relative to the Compose file
      - ./:/home/rails/webapp/:delegated
    volumes_from:
      - bundler-box
  bundler-box:
    image: busybox
    volumes:
    - /bundler-cache