version: '2'

app:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: .env
    command: sh ./script/start_app.sh
    volumes:
      # Path on the host, relative to the Compose file
      - ./:/home/rails/webapp/:delegated
    volumes_from:
      - bundler-box