common: &common
  adapter: postgresql
  username: kronos
  password: kronoskaplex # from psql setup, see Postgresql

development:
  <<: *common
  database: kronos_development

test:
  <<: *common
  database: kronos_test

production:
  <<: *common
  database: kronos_production