common: &common
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: db

development:
  <<: *common
  database: kronos_development

test:
  <<: *common
  database: kronos_test

production:
  <<: *common
  database: kronos_production
