name: Docker Image CD

on:
  push:
    branches: [ "master", "deployment-action" ]

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.5
      with:
        # ssh host
        host: kronos.nl
        # ssh port
        username: ${{ secrets.SSH_USERNAME }}
        # ssh password
        password: ${{ secrets.SSH_PASSWORD }}
        # synchronous execution if multiple hosts
        
        # execute commands
        script: |
          docker system prune -f
          cd /blockstorage
          docker-compose pull
          docker-compose down && docker-compose up -d
          
        
