name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # Username used to log against the Docker registry
        username: davkronos
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.docker_pswd }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        # List of tags
        tags: davkronos/kronos-website
        



